name: Publish Git to cpanel
on:
  push:
    branches:
       - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Upload files via SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host:  ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CPANEL_SSH_KEY }}
        port: 55005
        source: "."
        target: "/home/${{ secrets.USERNAME }}/public_html/"
