name: Publish Next.js to cPanel
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy Next.js
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🛠️ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗️ Build Next.js app
        run: npm run build

      - name: 📂 Upload files via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          port: 55005
          source: "."
          target: "/home/${{ secrets.USERNAME }}/public_html/frontend/"
          exclude: |
            .git
            .github
            .gitignore
            README.md